version: '3.8'

services:
  ui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cognyte-challenge-ui
    ports:
      - "3000:80"
    environment:
      - REACT_APP_API_URL
